# File name: Dockerfile
FROM rayproject/ray:2.9.3-py39-gpu

# Copy the entire project directory into the container
COPY . /home/ray/

# Install requirements
RUN pip install --upgrade pip
RUN pip install -Ur /home/ray/requirements-gcp.txt
RUN pip install --upgrade pyopenssl
